@@ -1,7 +1,3 @@
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
name: Build and deploy Python app to Azure Web App - SE4458-22070006085
name: Build and deploy Python app to Azure Web App - SE4458-22070006085


on:
on:
@@ -29,28 +25,23 @@ jobs:
      
      
      - name: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)


      - name: Zip artifact for deployment
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        run: zip -r release.zip . -x "venv/*" "*.git/*" ".github/*" "*.DS_Store"


      - name: Upload artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        uses: actions/upload-artifact@v4
        with:
        with:
          name: python-app
          name: python-app
          path: |
          path: release.zip
            release.zip
            !venv/


  deploy:
  deploy:
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    needs: build
    needs: build
    environment:
    environment:
      name: 'Production'
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
    permissions:
      id-token: write
      id-token: write #This is required for requesting the JWT


    steps:
    steps:
      - name: Download artifact from build job
      - name: Download artifact from build job
@@ -61,18 +52,16 @@ jobs:
      - name: Unzip artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip
        run: unzip release.zip


      
      - name: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        uses: azure/login@v2
        with:
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C90E34BF584742BAAC07336E0BB89743 }}
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C90E34BF584742BAAC07336E0BB89743 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7CD1B62CDE542FB8A63435D269F3F4D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7CD1B62CDE542FB8A63435D269F3F4D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98EC075D14CF43F6B3394CDC4177F237 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98EC075D14CF43F6B3394CDC4177F237 }}


      - name: 'Deploy to Azure Web App'
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        id: deploy-to-webapp
        with:
        with:
          app-name: 'SE4458-22070006085'
          app-name: 'SE4458-22070006085'
          slot-name: 'Production'
